INSERT INTO weapons (slug, name, category, cost, damage, fire_rate, ammo, reload, notes, damage_value, fire_rate_value) VALUES
('distortion', 'Distortion', 'primary', '700 Keys', '7.0x5', '0.40s', '77', NULL, 'Contraband rarity. Fires a 5-pellet spread (7 dmg each). Right-click creates a pulling vortex (12 stud radius, 30s cooldown).', 7.0, 0.4),
('energy-rifle', 'Energy Rifle', 'primary', '425 Keys, Energy Bundle', '20', '0.30s', '∞', NULL, 'Prime rarity.', 20.0, 0.3),
('flamethrower', 'Flamethrower', 'primary', '400 Keys, Heavy Duty Bundle', '85', 'Unconfirmed', '100/∞', NULL, 'Prime rarity.', 85.0, NULL),
('grenade-launcher', 'Grenade Launcher', 'primary', '425 Keys, Heavy Duty Bundle', '40', '0.60s', '6/24', '1.80s', 'Prime rarity.', 40.0, 0.6),
('crossbow', 'Crossbow', 'primary', '35 Keys', '37.5', '1.00s', '1/20', '1.15s', 'Standard rarity.', 37.5, 1.0),
('gunblade', 'Gunblade', 'primary', '45 Keys', '45', '0.75s', '12', NULL, 'Standard rarity. Hybrid ranged/melee weapon — also has a melee blade combo (35 dmg, 8 stud reach) and a dash.', 45.0, 0.75),
('scepter', 'Scepter', 'primary', 'Gamemode Exclusive (RIVALS RNG)', '25', 'Unconfirmed', '30', NULL, 'Contraband rarity. Gamemode-exclusive reward weapon (RIVALS RNG). Cooldown not documented by the source wiki.', 25.0, NULL),
('warper', 'Warper', 'secondary', '650 Keys, Season 1 Bundle (Retired)', '—', '0.25s', NULL, NULL, 'Contraband rarity. Teleport/mobility secondary — no direct damage. Cooldown 0.25s per use.', NULL, 0.25),
('energy-pistols', 'Energy Pistols', 'secondary', '400 Keys, Energy Bundle', '2.1', '0.03s', '∞', NULL, 'Prime rarity.', 2.1, 0.03),
('exogun', 'Exogun', 'secondary', '350 Keys, Exogun Bundle', '10 → 2 (falloff)', '0.28s', '6/28', '0.65s', 'Prime rarity.', 10.0, 0.28),
('slingshot', 'Slingshot', 'secondary', '300 Keys, Classic Bundle', '8', '0.10s', '99', NULL, 'Prime rarity.', 8.0, 0.1),
('flare-gun', 'Flare Gun', 'secondary', '10 Keys', '50', '0.25s', '1/1', '0.77s', 'Standard rarity.', 50.0, 0.25),
('glass-cannon', 'Glass Cannon', 'secondary', 'Gamemode Exclusive (RIVALS RNG/Gun Game)', '150', 'Unconfirmed', '1', NULL, 'Contraband rarity. Gamemode-exclusive (RIVALS RNG / Gun Game). One shot in the chamber (ammo 1) at high damage.', 150.0, NULL),
('maul', 'Maul', 'melee', '550 Keys, Season Pass (Retired)', '75', '1.00s', NULL, NULL, 'Prime rarity. Has a jump-slam attack in addition to normal swings.', 75.0, 1.0),
('spear', 'Spear', 'melee', 'Free (Season Pass)', '15', '0.50s', '3', NULL, 'Prime rarity. Melee combo damage shown; can also be thrown for 25 dmg (50 on critical), see wiki for full throw mechanics.', 15.0, 0.5),
('trowel', 'Trowel', 'melee', '200 Keys, Classic Bundle', '50', '0.60s', NULL, NULL, 'Prime rarity. Builds temporary brick cover in addition to its melee attack.', 50.0, 0.6),
('riot-shield', 'Riot Shield', 'melee', '45 Keys', '25', '0.70s', NULL, NULL, 'Standard rarity.', 25.0, 0.7),
('scythe', 'Scythe', 'melee', '40 Keys', '35', '0.70s', NULL, NULL, 'Standard rarity.', 35.0, 0.7),
('glast-shard', 'Glast Shard', 'melee', 'Gamemode Exclusive (RIVALS RNG/Gun Game)', '1', '0.60s', NULL, NULL, 'Contraband rarity.', 1.0, 0.6),
('grappler', 'Grappler', 'utility', 'Prime Bundle, Contraband Bundle', 'Unconfirmed', '8.00s', NULL, NULL, 'Contraband rarity. Grappling-hook mobility utility — no direct damage.', NULL, 8.0),
('subspace-tripmine', 'Subspace Tripmine', 'utility', '250 Keys, Classic Bundle', '149', '0.50s', '2', NULL, 'Prime rarity. Deployed trap; damage triggers on proximity.', 149.0, 0.5),
('warpstone', 'Warpstone', 'utility', '400 Keys', '1', '30.00s', NULL, NULL, 'Prime rarity. Teleport utility.', 1.0, 30.0),
('freeze-ray', 'Freeze Ray', 'utility', '45 Keys', '0', '0.50s', '1', NULL, 'Standard rarity. Slows/freezes on hit rather than dealing significant direct damage.', 0.0, 0.5),
('grenade', 'Grenade', 'utility', 'Free (0 Keys)', '1', '30.00s', NULL, NULL, 'Standard rarity.', 1.0, 30.0),
('jump-pad', 'Jump Pad', 'utility', '9 Jump Shards', '—', '0.50s', '3', NULL, 'Standard rarity. Deployable mobility utility — no direct damage.', NULL, 0.5),
('molotov', 'Molotov', 'utility', '25 Keys', '1', '30.00s', NULL, NULL, 'Standard rarity.', 1.0, 30.0),
('satchel', 'Satchel', 'utility', '35 Keys', '0', '0.50s', '3', NULL, 'Standard rarity.', 0.0, 0.5),
('smoke-grenade', 'Smoke Grenade', 'utility', '10 Keys', '1', '0.50s', '3', NULL, 'Standard rarity.', 1.0, 0.5),
('war-horn', 'War Horn', 'utility', '30 Keys', 'Unconfirmed', '45.00s', NULL, NULL, 'Standard rarity.', NULL, 45.0),
('elixir', 'Elixir', 'utility', 'Gamemode Exclusive (RIVALS RNG)', '50', '30.00s', NULL, NULL, 'Contraband rarity.', 50.0, 30.0),
('rng-dice', 'RNG Dice', 'utility', 'Gamemode Exclusive (RIVALS RNG)', '—', '4.00s', NULL, NULL, 'Contraband rarity. Gamemode-exclusive (RIVALS RNG) — random-effect utility, no fixed damage.', NULL, 4.0);
