INSERT INTO weapons (slug, name, category, cost, damage, fire_rate, ammo, reload, notes, damage_value, fire_rate_value) VALUES
('assault-rifle', 'Assault Rifle', 'primary', 'Free', '12 → 3 (falloff)', '0.10s', '20 / 100', '1.56s', 'Default starter primary, reliable at all ranges.', 12, 0.10),
('bow', 'Bow', 'primary', '15 Keys', '30 / 37.5 / 45 / 60 (draw stages)', '0.25s', '1 / 30', '0.19s', NULL, 60, 0.25),
('shotgun', 'Shotgun', 'primary', '20 Keys', '8x10 → 2.5x10 (falloff)', '0.70s', '7 / 35', NULL, NULL, 80, 0.70),
('burst-rifle', 'Burst Rifle', 'primary', '25 Keys', '20 → 5 (falloff)', '0.60s', '12 / 60', '1.60s', 'Body damage was reported nerfed 20→18 in the March 2026 "Lucky Update" — pending confirmation against current patch notes.', 20, 0.60),
('rpg', 'RPG', 'primary', '25 Keys', '50', '0.25s', '1 / 17', '1.04s', 'Explosive splash, applies a movement speed slow on hit.', 50, 0.25),
('sniper', 'Sniper', 'primary', '75 Keys', '50 body / reported one-shot headshot', '1.50s', '4 / 12', '1.80s', 'Movement speed penalty while equipped.', 50, 1.50),
('permafrost', 'Permafrost', 'primary', '700 Keys', '14 per bullet (2-round burst)', 'Burst', NULL, NULL, 'Contraband rarity. On-hit slow (up to -50% move speed) and a freeze ability. Full stat sheet (reload, magazine, range) not yet confirmed from an official source — flagged for follow-up.', 14, NULL),
('paintball-gun', 'Paintball Gun', 'primary', 'Unconfirmed', '22 per shot', 'Fast (exact figure unconfirmed)', NULL, NULL, 'Prime rarity. Full stat sheet not yet confirmed from an official source — flagged for follow-up.', 22, NULL),
('compound-bow', 'Compound Bow', 'primary', 'Unconfirmed', 'Unconfirmed', 'Unconfirmed', NULL, NULL, 'Heavy Draw mechanic pierces Riot Shields. Low projectile velocity requires leading shots. Full stat sheet not yet confirmed — flagged for follow-up.', NULL, NULL),
('minigun', 'Minigun', 'primary', 'Unconfirmed', 'Unconfirmed', 'Sustained, has spin-up time', NULL, NULL, 'Prime rarity. Mobility penalty while firing. Full stat sheet not yet confirmed — flagged for follow-up.', NULL, NULL),
('handgun', 'Handgun', 'secondary', 'Free', '12 → 3 (falloff)', '0.13s', '13 / 91', '1.06s', NULL, 12, 0.13),
('spray', 'Spray', 'secondary', '5 Keys', '8 → 2 (falloff)', '0.50s', '30 / 90', '1.30s', NULL, 8, 0.50),
('shorty', 'Shorty', 'secondary', '20 Keys', '7.5x10 → 2.5x10 (falloff)', '0.12s', '2 / 18', '1.70s', NULL, 75, 0.12),
('uzi', 'Uzi', 'secondary', '20 Keys', '8 → 2 (falloff)', '0.07s', '27 / 108', '1.50s', NULL, 8, 0.07),
('revolver', 'Revolver', 'secondary', '25 Keys', '30 → 8 (falloff)', '0.40s', '6 / 36', '1.80s', NULL, 30, 0.40),
('fists', 'Fists', 'melee', 'Free', '30', '0.35s', NULL, NULL, NULL, 30, 0.35),
('chainsaw', 'Chainsaw', 'melee', '15 Keys', '60', '0.60s', '150 fuel', NULL, NULL, 60, 0.60),
('knife', 'Knife', 'melee', '20 Keys', '40', '0.60s', NULL, NULL, NULL, 40, 0.60),
('katana', 'Katana', 'melee', '45 Keys', '45', '0.70s', NULL, NULL, NULL, 45, 0.70),
('battle-axe', 'Battle Axe', 'melee', '50 Keys', '55', '0.70s', NULL, NULL, NULL, 55, 0.70),
('flashbang', 'Flashbang', 'utility', '15 Keys', '—', '0.50s cooldown', '2', NULL, NULL, NULL, NULL),
('medkit', 'Medkit', 'utility', '300 Keys', '—', '90.00s cooldown', NULL, NULL, 'Heals over time when activated.', NULL, NULL);

INSERT INTO codes (code, reward, status) VALUES
('RIVALSSUMMER', '3x Tropical Chest', 'active'),
('COCONUTBONK', '250x Pearls', 'active'),
('CANNONBALLLLL', '5x Goodie Bag', 'active'),
('FREE194', '3x Keys', 'active'),
('FREE191', '3x Keys', 'active'),
('COMMUNITY24', '1x Community Wrap', 'active'),
('BONUS', '1x Key', 'active'),
('BOOST', '1x Key', 'active');

INSERT INTO tier_list (weapon_slug, weapon_name, tier, reason) VALUES
('permafrost', 'Permafrost', 'S', '2-round burst at 14 dmg/bullet with a freeze/slow effect (up to -50% move speed) that locks opponents down. Contraband rarity, 700 Keys.'),
('paintball-gun', 'Paintball Gun', 'S', '22 damage per shot with the fastest practical fire rate among primaries; rewards tracking aim at the mid-range most fights happen at.'),
('sniper', 'Sniper', 'A', '50 body damage, reportedly a guaranteed kill on headshot. High skill ceiling — the -20% move speed penalty punishes bad positioning.'),
('assault-rifle', 'Assault Rifle', 'A', 'Best free weapon in the game: 12 dmg at a 0.10s fire rate with a 20/100 ammo pool. Season 3 traded a damage nerf (13→12) for a fire-rate buff (0.11s→0.10s).'),
('compound-bow', 'Compound Bow', 'A', 'High skill/high reward: pierces Riot Shields via its Heavy Draw mechanic, but low projectile velocity means shots must be heavily led.'),
('burst-rifle', 'Burst Rifle', 'B', 'Strong close-mid range value at only 25 Keys, even after the March 2026 Lucky Update nerfed body damage.'),
('minigun', 'Minigun', 'B', 'Shreds groups on sustained fire, but spin-up time and a mobility penalty make it weak in 1v1 openings.');

INSERT INTO maps (name, category, notes) VALUES
('Arena', 'regular', NULL),
('Backrooms', 'regular', NULL),
('Battleground', 'regular', NULL),
('Bridge', 'regular', NULL),
('Chess', 'regular', 'Giant chessboard with numbered edges for orientation; open layout with chess pieces as cover, works for both long-range and close-quarters.'),
('Crossroads', 'regular', NULL),
('Construction', 'regular', 'Mirrored map with a crane and dangling crate; players spawn on a gap-filled second-floor area that''s easy to fall through.'),
('Dimension', 'regular', NULL),
('Docks', 'regular', NULL),
('Graveyard', 'regular', NULL),
('Iceberg', 'regular', NULL),
('Onyx', 'regular', NULL),
('Playground', 'regular', NULL),
('Splash', 'regular', NULL),
('Station', 'regular', 'Former battle-royale lobby, revamped for RIVALS in early 2024; Western-themed train station with two buildings and breakable windows.'),
('Shooting Range', 'regular', 'Tutorial map; also where the Codes/Rewards feature gets unlocked.'),
('Village', 'regular', NULL),
('Diorama Westown', 'regular', 'Added in Season 3 (April 2026), Hollywood-themed.'),
('Diorama Museum', 'regular', 'Added in Season 3 (April 2026), Hollywood-themed.'),
('Diorama Studio', 'regular', 'Added in Season 3 (April 2026), Hollywood-themed.'),
('Big Arena', 'big', NULL),
('Big Backrooms', 'big', NULL),
('Big Crossroads', 'big', NULL),
('Big Graveyard', 'big', NULL),
('Big Onyx', 'big', NULL),
('Big Splash', 'big', NULL),
('Big Station', 'big', NULL),
('Legacy Backrooms', 'legacy', 'Private servers only.'),
('Legacy Battleground', 'legacy', 'Private servers only.'),
('Legacy Crossroads', 'legacy', 'Private servers only.'),
('Legacy Docks', 'legacy', 'Private servers only.'),
('Legacy Onyx', 'legacy', 'Private servers only.'),
('Legacy Sandbox', 'legacy', 'Private servers only.'),
('Legacy Splash', 'legacy', 'Private servers only.'),
('Legacy Big Splash', 'legacy', 'Private servers only.');

INSERT INTO rank_tiers (name, has_sub_tiers, notes, sort_order) VALUES
('Bronze', 1, NULL, 1),
('Silver', 1, NULL, 2),
('Gold', 1, NULL, 3),
('Platinum', 1, 'Rank protection starts to fade here — losing at the bottom of the tier can demote you quickly.', 4),
('Diamond', 1, NULL, 5),
('Onyx', 1, NULL, 6),
('Nemesis', 0, 'No sub-tiers, above Onyx.', 7),
('Archnemesis', 0, 'Top of the ladder. Global Top 200 Archnemesis players can earn Mythical cosmetics each season.', 8);
