import raw from "./generated/codes.json";

export interface RivalsCode {
  code: string;
  reward: string;
  status: "active" | "expired";
}

// Data lives in Cloudflare D1 (rivalwiki-db); this reads a committed JSON
// snapshot generated by `npm run sync-d1`. Run that script again after
// editing rows in D1.
export const codes: RivalsCode[] = raw as RivalsCode[];

// Original data provenance (before it was loaded into D1). Codes expire
// quickly and individual outlets disagree on status — treat "active" as
// "reported active by at least one outlet as of lastChecked", not a guarantee.
export const CODES_SOURCE = {
  label: "Aggregated from PCGamesN, PC Gamer, Dexerto, RobloxDen, Beebom, Destructoid",
  lastChecked: "2026-08-31",
};

export const HOW_TO_REDEEM = [
  "Reach the shooting range tutorial and complete the first six tasks — this unlocks the Rewards feature.",
  'Open the menu, select "Rewards", and follow the developer accounts it prompts you to follow.',
  "Enter your Roblox username in the text box and hit Redeem to verify.",
  "Enter a code above and hit Redeem again.",
];
