import raw from "./generated/maps.json";

export type MapCategory = "regular" | "big" | "legacy";

export interface RivalsMap {
  name: string;
  category: MapCategory;
  notes?: string;
}

interface MapRow {
  name: string;
  category: MapCategory;
  notes: string | null;
}

// Data lives in Cloudflare D1 (rivalwiki-db); this reads a committed JSON
// snapshot generated by `npm run sync-d1`. Run that script again after
// editing rows in D1.
export const maps: RivalsMap[] = (raw as MapRow[]).map((r) => ({
  name: r.name,
  category: r.category,
  notes: r.notes ?? undefined,
}));

// Original data provenance (before it was loaded into D1). Total map count
// differs slightly between sources depending on update timing — treat the
// exact count as approximate, not a guaranteed live total.
export const MAPS_SOURCE = {
  label: "RIVALS Fandom wiki + bloxodes.com map listings",
  lastChecked: "2026-08-31",
};
