import raw from "./generated/rank_tiers.json";

export interface RankTier {
  name: string;
  hasSubTiers: boolean;
  notes?: string;
}

interface RankTierRow {
  name: string;
  has_sub_tiers: number;
  notes: string | null;
  sort_order: number;
}

// Data lives in Cloudflare D1 (rivalwiki-db); this reads a committed JSON
// snapshot generated by `npm run sync-d1`. Run that script again after
// editing rows in D1.
export const rankTiers: RankTier[] = (raw as RankTierRow[]).map((r) => ({
  name: r.name,
  hasSubTiers: r.has_sub_tiers === 1,
  notes: r.notes ?? undefined,
}));

// Original data provenance (before it was loaded into D1). Exact ELO
// thresholds/rewards shift between seasons — check the in-game ranked tab
// for current numbers, this page covers the structure, not live thresholds.
export const RANKS_SOURCE = {
  label: "Aggregated from allthings.how, GeekChamp, RivalsHub ranked guides",
  lastChecked: "2026-08-31",
};

export const RANKED_REQUIREMENTS = [
  "Complete 10 standard (unranked) duels first — wins and losses both count.",
  "Verify your account: phone number, Robux spend, or ID verification (email verification does not count).",
  "Your Roblox account must be at least 14 days old.",
  "Complete 10 placement matches to reveal your initial rank.",
];

export const RANKED_MECHANICS = [
  "Every ranked match adds or subtracts ELO. The amount depends on the gap between your ELO and your opponent's — beating someone several tiers above you swings your ELO more than beating someone near your level.",
  "Match outcome matters more than raw stats — high kills or damage don't fully offset a loss, especially at higher ranks.",
  "Party members must stay within 4 tiers (≈800 ELO) of each other to queue together, and matchmaking averages party MMR — queueing with a much higher-ranked friend can put you against tougher opponents.",
  "Modes: 1v1, 2v2, and 3v3 are all part of Ranked.",
];
