import raw from "./generated/tier_list.json";

export type Tier = "S" | "A" | "B" | "C";

export interface TierEntry {
  weaponSlug: string;
  weaponName: string;
  tier: Tier;
  reason: string;
}

interface TierRow {
  weapon_slug: string;
  weapon_name: string;
  tier: Tier;
  reason: string;
}

// Data lives in Cloudflare D1 (rivalwiki-db); this reads a committed JSON
// snapshot generated by `npm run sync-d1`. Run that script again after
// editing rows in D1.
export const tierList: TierEntry[] = (raw as TierRow[]).map((r) => ({
  weaponSlug: r.weapon_slug,
  weaponName: r.weapon_name,
  tier: r.tier,
  reason: r.reason,
}));

// This is explicitly an AGGREGATE of what multiple outlets are currently
// saying, not an in-house playtest ranking — other RIVALS sites disagree
// with each other on tier placement, so we cite reasoning per entry instead
// of presenting a bare list. Weapons we found no meta commentary for are
// left off rather than guessed at; see /weapons for the full roster.
export const TIER_LIST_SOURCE = {
  label: "Aggregated from BloxSpot, U7BUY, DungeonPath, community reporting",
  lastChecked: "2026-08-31",
};
