import raw from "./generated/weapons.json";

export type WeaponCategory = "primary" | "secondary" | "melee" | "utility";

export interface Weapon {
  slug: string;
  name: string;
  category: WeaponCategory;
  cost: string;
  damage: string;
  fireRate: string;
  ammo?: string;
  reload?: string;
  notes?: string;
  /** Close-range peak damage per shot/swing, for the visual stat bar. Omitted where not confidently derivable from the source data. */
  damageValue?: number;
  /** Seconds between shots/swings — lower is faster. Omitted for burst/unconfirmed weapons. */
  fireRateValue?: number;
}

interface WeaponRow {
  slug: string;
  name: string;
  category: WeaponCategory;
  cost: string;
  damage: string;
  fire_rate: string;
  ammo: string | null;
  reload: string | null;
  notes: string | null;
  damage_value: number | null;
  fire_rate_value: number | null;
}

// Data lives in Cloudflare D1 (rivalwiki-db); this file reads a committed
// JSON snapshot generated by `npm run sync-d1` so `next build` never needs
// live DB access. Run that script again after editing rows in D1.
export const weapons: Weapon[] = (raw as WeaponRow[]).map((r) => ({
  slug: r.slug,
  name: r.name,
  category: r.category,
  cost: r.cost,
  damage: r.damage,
  fireRate: r.fire_rate,
  ammo: r.ammo ?? undefined,
  reload: r.reload ?? undefined,
  notes: r.notes ?? undefined,
  damageValue: r.damage_value ?? undefined,
  fireRateValue: r.fire_rate_value ?? undefined,
}));

// Original data provenance (before it was loaded into D1) — not pulled from
// an official Nosniy Games stat sheet, treat as community-verified.
export const DATA_SOURCE = {
  label: "BloxGuidesGG weapons database (community, synced from RIVALS Fandom wiki)",
  url: "https://bloxguidesgg.com/games/rivals/wiki/weapons",
  lastChecked: "2026-08-31",
};

export function getWeapon(slug: string) {
  return weapons.find((w) => w.slug === slug);
}

export function weaponsByCategory(category: WeaponCategory) {
  return weapons.filter((w) => w.category === category);
}

export const MAX_DAMAGE_VALUE = Math.max(...weapons.map((w) => w.damageValue ?? 0));
export const MAX_FIRE_RATE_VALUE = Math.max(...weapons.map((w) => w.fireRateValue ?? 0));
